#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Baut alle 50 LK-Basis-Karten (Vorder-/Rückseite PNG) aus LK_Kartenkonzept_Entwurf.md
und LK_Tipps_fuer_dich_Entwurf.md. (30 Basis + 20 neu: Klassengemeinschaft, Abgrenzung & Feierabend,
Interkulturelle Kompetenz, KI & Digitalität, ergänzt 30.07.2026)"""
import os, glob, sys
sys.path.insert(0, os.path.dirname(__file__))
from build_card_lk import build_front, build_back

BILDER = "/sessions/kind-beautiful-ptolemy/mnt/klartext-app/bilder/lk/"
OUT = "/sessions/kind-beautiful-ptolemy/mnt/outputs/lk_karten_komplett/"
os.makedirs(OUT, exist_ok=True)

def find_image(nr):
    for pattern in (f"LK-R-{nr:02d}.jpg", f"LK-R-{nr:02d} *.jpg", f"LK-R-{nr:02d}.jpeg", f"LK-R-{nr:02d}.png"):
        files = sorted(glob.glob(os.path.join(BILDER, pattern)))
        if files:
            return files[0]
    return None

# nr: (titel, anleitung, [frage1, frage2], tipp_fuer_dich)
CARDS = {
    1: ("Meine Rolle gerade",
        "Guter Einstieg, um den aktuellen Stand der eigenen Rolle bewusst zu machen.",
        ["Wie würdest du deine Rolle als Lehrkraft gerade in einem Satz beschreiben?", "Was hat sich daran in letzter Zeit verändert?"],
        "Es gibt keine falsche Antwort. Die Rolle darf sich auch von Woche zu Woche anders anfühlen."),
    2: ("Zwischen Fördern und Fordern",
        "Für Momente, in denen Unterstützung und Anspruch in Spannung stehen.",
        ["Wo merkst du gerade, dass du besonders viel auffängst?", "Was würde passieren, wenn du diesem Kind an einer Stelle bewusst mehr zutraust?"],
        "Einem Kind an einer Stelle mehr zuzutrauen heißt nicht, insgesamt weniger zu unterstützen."),
    3: ("Erwartungen an mich selbst",
        "Eigene, oft unausgesprochene Ansprüche an die eigene Lehrrolle sichtbar machen.",
        ["Was erwartest du eigentlich von dir selbst als Lehrkraft?", "Woher kommt dieser Anspruch?"],
        "Oft stammen die höchsten Ansprüche aus der eigenen Ausbildung oder aus Vorbildern, nicht aus der aktuellen Situation."),
    4: ("Wenn Eltern meinen Unterricht infrage stellen",
        "Bei Kritik von Eltern oder Erziehungsberechtigten einsetzbar.",
        ["Wessen Kritik trifft dich dabei am meisten?", "Was würdest du dir stattdessen wünschen zu hören?"],
        "Nicht jede Kritik verdient ein Nachdenken – manche darf auch einfach vorbeiziehen."),
    5: ("Verantwortung teilen können",
        "Für Situationen, in denen Verantwortung ungleich verteilt ist (Team, Schulleitung, INGRA, Eltern).",
        ["Was trägst du gerade allein, das eigentlich geteilt werden könnte?", "Wer könnte dir davon etwas abnehmen?"],
        "Um Unterstützung bitten ist keine Schwäche, sondern oft der erste Schritt zu mehr Kraft für das Wesentliche."),
    6: ("Was dieses Kind gerade wirklich braucht",
        "Für Momente, in denen das Verhalten eines Kindes im Unterricht schwer zu deuten ist.",
        ["Was zeigt dir dieses Kind gerade mit seinem Verhalten?", "Was könnte dahinterstecken, auch wenn es auf den ersten Blick nicht so wirkt?"],
        "Besonders hilfreich, wenn ein Verhalten gerade unverständlich wirkt."),
    7: ("Verhalten hinter dem Verhalten",
        "Hilfreich, wenn ein Verhalten im Unterricht provoziert statt Verständnis auslöst.",
        ["Welches Gefühl steckt vermutlich hinter diesem Verhalten?", "Wie würdest du reagieren, wenn du nur das Gefühl sehen würdest, nicht das Verhalten?"],
        "Schwieriges Verhalten ist fast immer ein Hinweis, kein Angriff."),
    8: ("Wenn ich ein Kind nicht verstehe",
        "Entlastend einsetzen – nicht jedes Verhalten muss sofort erklärbar sein.",
        ["Welches Kind ist dir gerade ein Rätsel?", "Ist es okay, das gerade nicht zu verstehen?"],
        "Nicht-Verstehen ist kein Versagen als Lehrkraft, nur ein ehrlicher Zwischenstand."),
    9: ("Unterschiede zwischen Schüler:innen",
        "Für den Umgang mit heterogenen Klassen, besonders wenn einzelne Kinder mehr Aufmerksamkeit brauchen.",
        ["Wo fällt es dir schwer, alle Kinder gleich zu behandeln?", "Muss Gerechtigkeit eigentlich Gleichheit bedeuten?"],
        "Gerechtigkeit heißt oft, jedem Kind das zu geben, was es gerade braucht – nicht dasselbe."),
    10: ("Ein Kind mit anderen Augen sehen",
         "Guter Perspektivwechsel-Impuls, um eingefahrene Sichtweisen zu lockern.",
         ["Was würde eine Person, die dieses Kind mag, an ihm hervorheben?", "Wann hast du das zuletzt selbst so gesehen?"],
         "Guter Impuls für Tage, an denen der Blick auf ein Kind besonders kritisch geworden ist."),
    11: ("Zuhören, ohne gleich zu lösen",
         "Für Situationen, in denen ein Kind eigentlich nur gehört werden will.",
         ["Wann hast du zuletzt zugehört, ohne gleich eine Lösung anzubieten?", "Was würde sich ändern, wenn du das öfter tust?"],
         "Manchmal ist die beste Hilfe, gar keine Lösung anzubieten."),
    12: ("Wenn Gespräche eskalieren",
         "Rückblickend nach einem eskalierten Gespräch (mit Kind oder Eltern) einsetzbar, nicht mittendrin.",
         ["An welchem Punkt kippt ein Gespräch bei dir meistens?", "Was könntest du an diesem Punkt anders machen?"],
         "Am hilfreichsten mit etwas Abstand zum letzten Gespräch, nicht mittendrin."),
    13: ("Grenzen setzen, ohne die Beziehung zu belasten",
         "Für die Sorge, dass Grenzen die Beziehung zum Kind gefährden könnten.",
         ["Welche Grenze fällt dir besonders schwer zu setzen?", "Was befürchtest du, wenn du sie setzt?"],
         "Klare Grenzen und eine gute Beziehung schließen sich nicht aus."),
    14: ("Ehrlich sein, ohne zu überfordern",
         "Bei der Frage, wie viel ein Kind über schwierige Themen wissen sollte.",
         ["Wo hältst du dich gerade zurück, um ein Kind zu schützen?", "Was wäre eine altersgerechte Version der Wahrheit?"],
         "Ehrlichkeit lässt sich fast immer altersgerecht dosieren, ganz weglassen muss sie nicht."),
    15: ("Mit dem Kollegium an einem Strang",
         "Für Teams mit unterschiedlichen pädagogischen Ansätzen, nicht als Schuldzuweisung gedacht.",
         ["Wo unterscheidet ihr euch am meisten im Umgang mit einem Kind?", "Was habt ihr trotzdem gemeinsam?"],
         "Nicht als Schuldfrage lesen – unterschiedliche Ansätze sind normal, nicht falsch."),
    16: ("Wenn ein Kind gemobbt wird",
         "Bei akuten Ausgrenzungs-/Mobbingerfahrungen in der Klasse.",
         ["Was brauchst du gerade selbst, um in dieser Situation klar handeln zu können?", "Wer kann dich dabei unterstützen?"],
         "Erst selbst klar werden, bevor du wirksam handeln kannst – das ist keine falsche Reihenfolge."),
    17: ("Wenn ich mich hilflos fühle",
         "Entlastend für Momente, in denen keine Lösung greifbar scheint.",
         ["Wann fühlst du dich als Lehrkraft am hilflosesten?", "Was hilft dir, das auszuhalten, auch ohne Lösung?"],
         "Hilflosigkeit auszuhalten ist manchmal die eigentliche Aufgabe, nicht ein Zeichen, dass etwas fehlt."),
    18: ("Der erste Schock nach einer schwierigen Nachricht zu einem Kind",
         "Für die erste Zeit nach einer belastenden Information (Diagnose, familiäre Situation, Vorfall).",
         ["Was hat sich für dich durch diese Nachricht verändert?", "Was bleibt trotzdem gleich?"],
         "Gib dir Zeit – diese Karte eignet sich nicht für den ersten Tag, eher für die Wochen danach."),
    19: ("Umgang mit Eltern in schwierigen Momenten",
         "Bei Spannungen zwischen Schule und Elternhaus.",
         ["Was wünschst du dir gerade am meisten von diesem Elternhaus?", "Was könntest du selbst dazu beitragen, dass es besser läuft?"],
         "Auch berechtigte Anliegen dürfen ruhig und bestimmt vorgetragen werden, nicht nur laut."),
    20: ("Wenn eine Krise vorbei ist",
         "Rückblickend nach überstandenen schwierigen Phasen in der Klasse.",
         ["Was hat euch als Klasse/Team durch die letzte schwierige Zeit getragen?", "Was nimmst du daraus mit?"],
         "Guter Moment, um festzuhalten, was diesmal geholfen hat – für die nächste schwierige Phase."),
    21: ("Der Unterrichtstag, der nie stressfrei ist",
         "Für wiederkehrenden Alltagsstress, niedrigschwellig einsetzbar.",
         ["Was macht deinen Unterrichtstag am meisten stressig?", "Was wäre ein kleiner, realistischer erster Schritt?"],
         "Kleine Veränderungen wirken hier oft mehr als ein kompletter Neustart."),
    22: ("Differenzierung ohne Überforderung",
         "Bei dem Anspruch, allen Kindern gleichzeitig gerecht zu werden.",
         ["Wo genau wird Differenzierung für dich am anstrengendsten?", "Was könntest du bewusst vereinfachen?"],
         "Nicht jede Differenzierung muss perfekt sein, um zu wirken."),
    23: ("Streit in der Klasse",
         "Für den Umgang mit wiederkehrendem Streit zwischen Schüler:innen.",
         ["Musst du wirklich jeden Streit schlichten?", "Was würde passieren, wenn du dich öfter zurückhältst?"],
         "Nicht jeder Streit braucht ein Urteil von dir."),
    24: ("Verwaltung, Dokumentation, Formulare – der bürokratische Alltag",
         "Entlastend für die organisatorische Seite des Lehrberufs.",
         ["Was an der Verwaltung belastet dich gerade am meisten?", "Was könntest du abgeben oder vereinfachen?"],
         "Auch Verwaltung darf an einem entlasteten Tag bearbeitet werden, nicht nur unter Druck."),
    25: ("Wenn der Schulalltag einfach zu viel wird",
         "Für allgemeine Überforderung, nicht an eine konkrete Situation gebunden.",
         ["Was würdest du gerade als Erstes weglassen, wenn du dürftest?", "Wer könnte dir eine Aufgabe abnehmen?"],
         "Ein einzelner weggelassener Punkt macht selten den Unterschied, den du befürchtest."),
    26: ("Meine eigenen Grenzen erkennen",
         "Für Lehrkräfte, die sich selbst oft zuletzt sehen.",
         ["Woran merkst du, dass du an deine Grenze kommst?", "Was tust du normalerweise, kurz bevor es zu viel wird?"],
         "Deine Grenze zu kennen schützt am Ende auch deinen Unterricht."),
    27: ("Schuldgefühle als Lehrkraft",
         "Sehr verbreitetes Thema, entlastend statt bewertend einsetzen.",
         ["Wofür machst du dir gerade am meisten Vorwürfe?", "Würdest du das auch einer anderen Person so vorwerfen?"],
         "Fast jede Lehrkraft kennt dieses Gefühl – das macht es nicht automatisch berechtigt."),
    28: ("Der Vergleich mit anderen Lehrkräften",
         "Bei Selbstzweifeln durch Vergleiche im Kollegium.",
         ["Mit wem vergleichst du dich am meisten?", "Was siehst du bei der anderen Person nicht?"],
         "Was du bei anderen siehst, ist fast nie ihr ganzer Alltag."),
    29: ("Kleine Momente für mich",
         "Ressourcenorientiert, um eigene kleine Auszeiten im Schulalltag sichtbar zu machen.",
         ["Wann hattest du zuletzt einen Moment nur für dich?", "Was wäre ein realistischer kleiner Moment diese Woche?"],
         "Auch fünf Minuten zählen – es muss keine große Auszeit sein."),
    30: ("Worauf ich stolz sein darf",
         "Guter Abschluss-Impuls, wertschätzender Rückblick statt Bewertung.",
         ["Worauf bist du als Lehrkraft stolz, wenn du zurückblickst?", "Was möchtest du dir selbst dafür sagen?"],
         "Guter Abschluss – bewusst als Rückblick lesen, nicht als Bewertung."),
    31: ("Was diese Klasse gerade als Gruppe braucht",
         "Für Momente, in denen der Blick zu stark auf einzelne Kinder verengt ist und die Klasse als Ganzes aus dem Blick gerät.",
         ["Was würde diese Klasse gerade als Gruppe am meisten brauchen?", "Wo unterscheidet sich das von dem, was ein einzelnes Kind gerade braucht?"],
         "Eine Klasse ist mehr als die Summe ihrer Kinder – manchmal hilft der Blick aufs Ganze mehr als die nächste Einzelmaßnahme."),
    32: ("Rollen, die sich in der Klasse festsetzen",
         "Für Klassen, in denen einzelne Kinder immer dieselbe Rolle einnehmen (Klassenclown, Sündenbock, stille Ecke).",
         ["Welche feste Rolle fällt dir bei einem Kind in dieser Klasse besonders auf?", "Wie trägst du selbst vielleicht dazu bei, dass diese Rolle bestehen bleibt?"],
         "Rollen entstehen oft über viele kleine Wiederholungen – sie lassen sich auch über kleine Wiederholungen wieder lockern."),
    33: ("Wenn eine Klasse unruhig wird",
         "Für Phasen, in denen sich Unruhe in der ganzen Klasse ausbreitet, nicht nur bei Einzelnen.",
         ["Seit wann genau ist diese Klasse unruhiger als sonst?", "Was hat sich um diesen Zeitpunkt herum verändert?"],
         "Unruhe in der Klasse hat fast immer einen Auslöser – er muss dir nur nicht sofort einleuchten."),
    34: ("Zusammenhalt fördern, ohne zu erzwingen",
         "Für den Wunsch nach mehr Gemeinschaftsgefühl, ohne dass es aufgesetzt wirkt.",
         ["Wann hast du diese Klasse zuletzt wirklich als Gemeinschaft erlebt?", "Was war in diesem Moment anders als sonst?"],
         "Zusammenhalt lässt sich selten anordnen, aber gute Gelegenheiten dafür lassen sich schaffen."),
    35: ("Wenn sich eine Klasse gegen dich stellt",
         "Für die belastende Erfahrung, als Lehrkraft von der ganzen Klasse abgelehnt oder getestet zu werden.",
         ["Woran genau merkst du, dass sich die Klasse gerade gegen dich stellt?", "Was hat sich kurz davor in eurer Beziehung verändert?"],
         "Das ist selten wirklich persönlich gemeint, auch wenn es sich in dem Moment genauso anfühlt."),
    36: ("Die Schule gedanklich verlassen",
         "Für den Übergang vom Schultag zum Feierabend, wenn Gedanken an die Schule einfach nicht aufhören.",
         ["Was beschäftigt dich gerade am meisten, wenn du eigentlich schon zu Hause bist?", "Was würde dir helfen, das für heute abzuschließen?"],
         "Der Kopf lässt sich nicht per Wille abschalten, aber ein wiederkehrendes Ritual kann ihm dabei helfen."),
    37: ("Erreichbarkeit außerhalb der Schulzeit",
         "Für die Frage, wie erreichbar man für Eltern, Kinder oder Kolleg:innen außerhalb der Arbeitszeit sein möchte.",
         ["Wie erreichbar bist du gerade tatsächlich außerhalb deiner Arbeitszeit?", "Ist das eine bewusste Entscheidung oder eher so entstanden?"],
         "Erreichbarkeit lässt sich bewusst gestalten – auch rückwirkend, wenn sie sich unbemerkt eingeschlichen hat."),
    38: ("Das Wochenende als echte Pause",
         "Für Wochenenden, die durch Vorbereitung und Korrekturen kaum als Pause spürbar sind.",
         ["Wie viel von deinem letzten Wochenende war eigentlich Schule?", "Was würde ein Wochenende brauchen, damit es sich wirklich wie eine Pause anfühlt?"],
         "Erholung entsteht nicht automatisch durch freie Zeit, sondern durch Zeit, die auch wirklich frei bleibt."),
    39: ("Wenn die Ferien nicht wie Erholung wirken",
         "Für die verbreitete Erfahrung, dass auch Ferien nicht als echte Erholung ankommen.",
         ["Was braucht eine Pause bei dir, um wirklich als Pause zu wirken?", "Was hindert dich manchmal daran, sie dir zu nehmen?"],
         "Erholung braucht oft mehr als freie Zeit – manchmal auch die innere Erlaubnis, sie zu nutzen."),
    40: ("Die Schule mit nach Hause tragen",
         "Für das Gefühl, dass belastende Situationen aus der Schule noch lange nachwirken, auch zu Hause.",
         ["Welche Situation aus der Schule trägst du gerade noch mit dir herum?", "Was würde dir helfen, sie für heute abzulegen, auch wenn sie morgen wieder da ist?"],
         "Manche Dinge lassen sich nicht an einem Abend lösen – sie dürfen trotzdem für den Abend beiseitegelegt werden."),
    41: ("Verschiedene Vorstellungen von Erziehung",
         "Für Elterngespräche, in denen sich Erziehungsvorstellungen deutlich unterscheiden.",
         ["Welche Erziehungsvorstellung eines Elternhauses irritiert dich gerade am meisten?", "Was könnte dahinter für eine eigene Logik stecken, auch wenn du sie nicht teilst?"],
         "Eine andere Erziehungsvorstellung ist nicht automatisch eine schlechtere – nur eine andere."),
    42: ("Wenn Sprache eine Barriere ist",
         "Für Elterngespräche oder Unterrichtssituationen, in denen Sprache das Verständnis erschwert.",
         ["Wo genau entsteht das Missverständnis – an der Sprache oder an etwas dahinter?", "Was hilft dir sonst, wenn Worte allein nicht reichen?"],
         "Verständigung gelingt auch mit wenigen gemeinsamen Worten, wenn Geduld und Geste dazukommen."),
    43: ("Zwischen zwei kulturellen Systemen",
         "Für Kinder, die zu Hause und in der Schule mit unterschiedlichen Regeln und Erwartungen aufwachsen.",
         ["Wo genau erlebt dieses Kind vermutlich die größte Spannung zwischen zu Hause und Schule?", "Wie könntest du diese Spannung sichtbar entlasten, statt sie zu verstärken?"],
         "Zwischen zwei Systemen zu leben ist anstrengend – schon das Anerkennen dieser Anstrengung kann entlasten."),
    44: ("Eigene blinde Flecken erkennen",
         "Für die ehrliche Reflexion eigener unbewusster Erwartungen oder Annahmen gegenüber Familien mit anderem kulturellen Hintergrund.",
         ["Welche unausgesprochene Erwartung hast du vielleicht an eine bestimmte Familie?", "Woher stammt diese Erwartung eigentlich?"],
         "Blinde Flecken zu erkennen ist kein Vorwurf an dich selbst, sondern ein Zeichen von Aufmerksamkeit."),
    45: ("Vielfalt als Ressource statt Herausforderung",
         "Guter Perspektivwechsel-Impuls, wenn kulturelle Vielfalt vor allem als zusätzlicher Aufwand erlebt wird.",
         ["Was bringt die Vielfalt in dieser Klasse tatsächlich Positives mit sich?", "Wann hast du das zuletzt bewusst wahrgenommen?"],
         "Vielfalt ist beides gleichzeitig – Aufwand und Bereicherung. Beides gilt, ohne sich gegenseitig aufzuheben."),
    46: ("Meine Rolle im digitalen Wandel",
         "Für die grundsätzliche Reflexion, wie sich die eigene Lehrrolle durch digitale Werkzeuge verändert.",
         ["Was an deiner Rolle als Lehrkraft verändert sich gerade durch digitale Werkzeuge?", "Was bleibt davon garantiert unverändert?"],
         "Der Wandel betrifft die Werkzeuge, nicht automatisch das, was eine gute Lehrkraft ausmacht."),
    47: ("Wenn KI Aufgaben übernimmt, die früher meine waren",
         "Für die Verunsicherung, wenn KI-Werkzeuge Aufgaben wie Textkorrektur oder Materialerstellung übernehmen.",
         ["Welche Aufgabe hast du zuletzt an ein digitales Werkzeug abgegeben?", "Wie hat sich das für dich angefühlt – entlastend, befremdlich, beides?"],
         "Abgeben ist keine Kapitulation – die Entscheidung, was du behältst, bleibt trotzdem bei dir."),
    48: ("Schüler:innen und KI im Unterricht",
         "Für den Umgang mit Schüler:innen, die KI-Werkzeuge selbstständig nutzen, etwa für Hausaufgaben.",
         ["Was beunruhigt dich am meisten daran, wenn Schüler:innen KI nutzen?", "Was würde ein offener, statt ein abwehrender Umgang damit für deinen Unterricht bedeuten?"],
         "Verbote allein verhindern selten die Nutzung – ein offener Umgang schafft eher echte Lernchancen."),
    49: ("Digitale Erschöpfung",
         "Für die zusätzliche Belastung durch Bildschirmzeit, digitale Kommunikation und ständige Erreichbarkeit über Schul-Apps und Mail.",
         ["Wie viel deines Arbeitstages verbringst du gerade vor einem Bildschirm?", "Wo könntest du bewusst eine bildschirmfreie Zeit einbauen?"],
         "Digitale Werkzeuge sollen Zeit schaffen – wenn sie das Gegenteil bewirken, darfst du sie hinterfragen."),
    50: ("Was ich an analogem Unterricht nicht verlieren möchte",
         "Guter Abschluss-Impuls, um bei aller Digitalisierung bewusst zu halten, was den eigenen Unterricht ausmacht.",
         ["Was an deinem Unterricht möchtest du auf keinen Fall durch digitale Werkzeuge ersetzen?", "Warum ist dir genau das so wichtig?"],
         "Digitalisierung muss kein Entweder-oder sein – du entscheidest, was ergänzt wird und was bleibt."),
}

SYSTEMFRAGEN = {
    1: ("SKALIERUNGSFRAGE", "Auf einer Skala von 1–10 – wie stimmig fühlt sich deine Rolle gerade an?"),
    2: ("HANDLUNGSFRAGE", "Was wäre ein kleiner Schritt, um diesem Kind an einer Stelle bewusst mehr zuzutrauen?"),
    3: ("ZIRKULÄRE FRAGE", "Was würde eine Kollegin/ein Kollege sagen, wenn sie/er deinen Anspruch an dich selbst hören würde?"),
    4: ("SKALIERUNGSFRAGE", "Auf einer Skala von 1–10 – wie sehr lässt du diese Kritik gerade an dich heran?"),
    5: ("HANDLUNGSFRAGE", "Was wäre ein erster, kleiner Schritt, um genau das abzugeben?"),
    6: ("ZIRKULÄRE FRAGE", "Was würde dieses Kind sagen, wenn es erklären könnte, was hinter seinem Verhalten steckt?"),
    7: ("ZIRKULÄRE FRAGE", "Wie würde eine außenstehende Person dieses Verhalten wohl deuten?"),
    8: ("SKALIERUNGSFRAGE", "Auf einer Skala von 1–10 – wie dringend fühlt sich das Nicht-Verstehen gerade an?"),
    9: ("HANDLUNGSFRAGE", "Was wäre ein kleiner Schritt, um dem Kind, das gerade zu kurz kommt, etwas mehr zu geben?"),
    10: ("SKALIERUNGSFRAGE", "Auf einer Skala von 1–10 – wie wohlwollend ist dein Blick auf dieses Kind gerade?"),
    11: ("HANDLUNGSFRAGE", "Was wäre ein kleiner Schritt, um beim nächsten Gespräch bewusst länger zuzuhören, bevor du antwortest?"),
    12: ("ZIRKULÄRE FRAGE", "Wie würde eine außenstehende Person den Punkt beschreiben, an dem das Gespräch kippt?"),
    13: ("SKALIERUNGSFRAGE", "Auf einer Skala von 1–10 – wie sicher fühlst du dich gerade beim Grenzensetzen?"),
    14: ("HANDLUNGSFRAGE", "Was wäre ein kleiner, altersgerechter erster Satz, den du sagen könntest?"),
    15: ("ZIRKULÄRE FRAGE", "Was würde dein Kollegium sagen, wenn es eure gemeinsamen Punkte beschreiben müsste?"),
    16: ("HANDLUNGSFRAGE", "Was wäre ein kleiner erster Schritt, um selbst Unterstützung zu holen?"),
    17: ("SKALIERUNGSFRAGE", "Auf einer Skala von 1–10 – wie stark ist das Gefühl von Hilflosigkeit gerade?"),
    18: ("SKALIERUNGSFRAGE", "Auf einer Skala von 1–10 – wie weit bist du gerade in der Verarbeitung?"),
    19: ("ZIRKULÄRE FRAGE", "Was würden die Eltern wohl sagen, wenn sie ihre Sicht auf die Zusammenarbeit beschreiben müssten?"),
    20: ("HANDLUNGSFRAGE", "Was möchtest du konkret festhalten, damit es dir beim nächsten Mal zur Verfügung steht?"),
    21: ("HANDLUNGSFRAGE", "Was wäre eine kleine, realistische Änderung, die du diese Woche ausprobieren könntest?"),
    22: ("HANDLUNGSFRAGE", "Was wäre ein kleiner Schritt, um bewusst etwas zu vereinfachen?"),
    23: ("SKALIERUNGSFRAGE", "Auf einer Skala von 1–10 – wie sehr ist es gerade wirklich dein Streit?"),
    24: ("HANDLUNGSFRAGE", "Was wäre ein kleiner Schritt, um etwas davon abzugeben oder zu vereinfachen?"),
    25: ("SKALIERUNGSFRAGE", "Auf einer Skala von 1–10 – wie voll fühlt sich dein Alltag gerade an?"),
    26: ("SKALIERUNGSFRAGE", "Auf einer Skala von 1–10 – wie nah bist du gerade an deiner Grenze?"),
    27: ("ZIRKULÄRE FRAGE", "Was würde eine gute Kollegin/ein guter Kollege zu diesem Vorwurf sagen, den du dir machst?"),
    28: ("ZIRKULÄRE FRAGE", "Was würde die andere Lehrkraft wohl über ihre eigenen schwierigen Momente sagen, die du nicht siehst?"),
    29: ("HANDLUNGSFRAGE", "Was wäre ein realistischer kleiner Moment, den du dir diese Woche konkret einplanst?"),
    30: ("SKALIERUNGSFRAGE", "Auf einer Skala von 1–10 – wie sehr erlaubst du dir gerade, stolz zu sein?"),
    31: ("ZIRKULÄRE FRAGE", "Was würde die Klasse sagen, wenn sie sich selbst als Gruppe beschreiben müsste?"),
    32: ("HANDLUNGSFRAGE", "Was wäre eine kleine Situation, in der du dieses Kind bewusst außerhalb seiner üblichen Rolle ansprechen könntest?"),
    33: ("SKALIERUNGSFRAGE", "Auf einer Skala von 1–10 – wie stark spürst du diese Unruhe gerade selbst mit?"),
    34: ("HANDLUNGSFRAGE", "Was wäre ein kleiner, echter Moment, den du diese Woche wieder ermöglichen könntest?"),
    35: ("ZIRKULÄRE FRAGE", "Was würde eine erfahrene Kollegin/ein erfahrener Kollege von außen an dieser Situation zuerst bemerken?"),
    36: ("HANDLUNGSFRAGE", "Was wäre ein kleines, festes Ritual für den Übergang von Schule zu Feierabend?"),
    37: ("SKALIERUNGSFRAGE", "Auf einer Skala von 1–10 – wie klar sind deine eigenen Grenzen bei der Erreichbarkeit gerade?"),
    38: ("HANDLUNGSFRAGE", "Was wäre ein kleiner, geschützter Zeitraum, den du dir dieses Wochenende bewusst freihältst?"),
    39: ("ZIRKULÄRE FRAGE", "Was würde eine Person, die dich gut kennt, dir für die nächsten Ferien raten?"),
    40: ("HANDLUNGSFRAGE", "Was wäre ein kleiner Schritt, um diese Situation heute Abend bewusst beiseitezulegen?"),
    41: ("ZIRKULÄRE FRAGE", "Was würden diese Eltern sagen, wenn sie ihre Sicht auf gute Erziehung erklären müssten?"),
    42: ("HANDLUNGSFRAGE", "Was wäre ein kleines, konkretes Hilfsmittel, das du beim nächsten Gespräch einsetzen könntest?"),
    43: ("ZIRKULÄRE FRAGE", "Was würde dieses Kind sagen, wenn es beschreiben müsste, wie sich die zwei Welten für es anfühlen?"),
    44: ("SKALIERUNGSFRAGE", "Auf einer Skala von 1–10 – wie sicher bist du dir gerade, dass deine Sicht auf diese Familie neutral ist?"),
    45: ("HANDLUNGSFRAGE", "Was wäre eine kleine Gelegenheit, diese Vielfalt in den nächsten Tagen sichtbar wertzuschätzen?"),
    46: ("SKALIERUNGSFRAGE", "Auf einer Skala von 1–10 – wie sicher fühlst du dich gerade im Umgang mit diesem Wandel?"),
    47: ("HANDLUNGSFRAGE", "Was wäre eine Aufgabe, bei der du bewusst entscheidest, sie weiterhin selbst zu machen?"),
    48: ("ZIRKULÄRE FRAGE", "Was würden die Schüler:innen sagen, wenn sie erklären müssten, warum sie diese Werkzeuge nutzen?"),
    49: ("HANDLUNGSFRAGE", "Was wäre ein konkreter, bildschirmfreier Moment, den du dir morgen bewusst nimmst?"),
    50: ("SKALIERUNGSFRAGE", "Auf einer Skala von 1–10 – wie gut gelingt es dir gerade, dieses Wichtige trotz aller Digitalisierung zu bewahren?"),
}

def run(nur=None, ueberspringen=()):
    ok, fehler, uebersprungen = [], [], []
    numbers = nur if nur else sorted(CARDS)
    for nr in numbers:
        if nr in ueberspringen:
            uebersprungen.append(nr)
            continue
        titel, anleitung, fragen, tipp = CARDS[nr]
        image_path = find_image(nr)
        if not image_path:
            fehler.append((nr, "Bild nicht gefunden"))
            continue
        card = {"nr": nr, "titel": titel, "anleitung": anleitung, "fragen": fragen, "hinweis": tipp,
                "systemfrage": SYSTEMFRAGEN.get(nr), "total": len(CARDS)}
        vorn = os.path.join(OUT, f"LK-R-{nr:02d}_Vorderseite.png")
        hinten = os.path.join(OUT, f"LK-R-{nr:02d}_Rueckseite.png")
        try:
            build_front(card, image_path, vorn)
            build_back(card, hinten)
            ok.append(nr)
        except Exception as e:
            fehler.append((nr, str(e)))
    print(f"Fertig: {len(ok)} Karten gebaut.")
    if uebersprungen:
        print("Übersprungen:", uebersprungen)
    if fehler:
        print("Fehler bei (fehlende Bilder):", fehler)

if __name__ == "__main__":
    run()
